//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiveDirectory
    {
        public int ID { get; set; }
        public string Usuario { get; set; }
        public string Nombre { get; set; }
        public string Puesto { get; set; }
        public string Area { get; set; }
        public string Correo { get; set; }
        public string Telefono { get; set; }
        public Nullable<int> CodigoScilu { get; set; }
        public string DPI { get; set; }
    }
}
