//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AITAvisoTarea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AITAvisoTarea()
        {
            this.AITAvisoTareaCausa = new HashSet<AITAvisoTareaCausa>();
            this.AITAvisoTareaMultimedia = new HashSet<AITAvisoTareaMultimedia>();
            this.AITAvisoTareaUsuario = new HashSet<AITAvisoTareaUsuario>();
        }
    
        public int CodigoAvisoTarea { get; set; }
        public int CodigoAviso { get; set; }
        public int CodigoEstadoTarea { get; set; }
        public int CodigoTareaTipo { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public string Comentario { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public bool Activo { get; set; }
        public bool Eliminado { get; set; }
        public string UsuarioInserto { get; set; }
        public System.DateTime FechaInserto { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
        public Nullable<int> Orden { get; set; }
    
        public virtual AITAviso AITAviso { get; set; }
        public virtual AITEstadoTarea AITEstadoTarea { get; set; }
        public virtual AITTareaTipo AITTareaTipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AITAvisoTareaCausa> AITAvisoTareaCausa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AITAvisoTareaMultimedia> AITAvisoTareaMultimedia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AITAvisoTareaUsuario> AITAvisoTareaUsuario { get; set; }
    }
}
