//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AITAviso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AITAviso()
        {
            this.AITAvisoCampoValor = new HashSet<AITAvisoCampoValor>();
            this.AITAvisoCausa = new HashSet<AITAvisoCausa>();
            this.AITAvisoMultimedia = new HashSet<AITAvisoMultimedia>();
            this.AITAvisoServicioReferencia = new HashSet<AITAvisoServicioReferencia>();
            this.AITAvisoTarea = new HashSet<AITAvisoTarea>();
            this.AITAvisoUsuario = new HashSet<AITAvisoUsuario>();
        }
    
        public int CodigoAviso { get; set; }
        public int CodigoProblema { get; set; }
        public int CodigoSolicitante { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public string ComentarioFinal { get; set; }
        public int CodigoEstado { get; set; }
        public bool Activo { get; set; }
        public bool Eliminado { get; set; }
        public string UsuarioInserto { get; set; }
        public System.DateTime FechaInserto { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
        public int CodigoUsuarioAfectado { get; set; }
        public Nullable<int> TiempoEjecucion { get; set; }
        public Nullable<decimal> Latitud { get; set; }
        public Nullable<decimal> Longitud { get; set; }
    
        public virtual AITEstado AITEstado { get; set; }
        public virtual AITProblema AITProblema { get; set; }
        public virtual AITUsuario AITUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AITAvisoCampoValor> AITAvisoCampoValor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AITAvisoCausa> AITAvisoCausa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AITAvisoMultimedia> AITAvisoMultimedia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AITAvisoServicioReferencia> AITAvisoServicioReferencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AITAvisoTarea> AITAvisoTarea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AITAvisoUsuario> AITAvisoUsuario { get; set; }
    }
}
