//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AITAvisoServicioReferencia
    {
        public int CodigoAvisoServicioReferencia { get; set; }
        public int CodigoAviso { get; set; }
        public int CodigoServicio { get; set; }
        public string Valor { get; set; }
        public bool Activo { get; set; }
        public bool Eliminado { get; set; }
        public string UsuarioInserto { get; set; }
        public System.DateTime FechaInserto { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
    
        public virtual AITAviso AITAviso { get; set; }
        public virtual AITServicio AITServicio { get; set; }
    }
}
