//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AITCampo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AITCampo()
        {
            this.AITAvisoCampoValor = new HashSet<AITAvisoCampoValor>();
            this.AITCampoCatalogoSeleccion = new HashSet<AITCampoCatalogoSeleccion>();
        }
    
        public int CodigoCampo { get; set; }
        public int CodigoPlantilla { get; set; }
        public int CodigoTipoCampo { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Llave { get; set; }
        public bool Requerido { get; set; }
        public int Orden { get; set; }
        public int ValorMinimo { get; set; }
        public int ValorMaximo { get; set; }
        public bool Activo { get; set; }
        public bool Eliminado { get; set; }
        public string UsuarioInserto { get; set; }
        public System.DateTime FechaInserto { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
        public string OrigenDatos { get; set; }
        public Nullable<int> CodigoCampoPadre { get; set; }
        public bool Visible { get; set; }
        public string ValorPorDefecto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AITAvisoCampoValor> AITAvisoCampoValor { get; set; }
        public virtual AITPlantilla AITPlantilla { get; set; }
        public virtual AITTipoCampo AITTipoCampo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AITCampoCatalogoSeleccion> AITCampoCatalogoSeleccion { get; set; }
    }
}
