//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AITCausa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AITCausa()
        {
            this.AITAvisoCausa = new HashSet<AITAvisoCausa>();
            this.AITAvisoTareaCausa = new HashSet<AITAvisoTareaCausa>();
            this.AITProblemaCausa = new HashSet<AITProblemaCausa>();
        }
    
        public int CodigoCausa { get; set; }
        public string Nombre { get; set; }
        public int TiempoEsperaEstimado { get; set; }
        public bool Activo { get; set; }
        public bool Eliminado { get; set; }
        public Nullable<int> CodigoSubEntidad { get; set; }
        public Nullable<bool> Publico { get; set; }
        public string UsuarioInserto { get; set; }
        public System.DateTime FechaInserto { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AITAvisoCausa> AITAvisoCausa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AITAvisoTareaCausa> AITAvisoTareaCausa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AITProblemaCausa> AITProblemaCausa { get; set; }
    }
}
