//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AITDashboard
    {
        public int CodigoDashboard { get; set; }
        public int CodigoDashboardTipo { get; set; }
        public int CodigoPermiso { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public string Endpoint { get; set; }
        public bool Activo { get; set; }
        public bool Eliminado { get; set; }
        public string UsuarioInserto { get; set; }
        public System.DateTime FechaInserto { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
    
        public virtual AITDashboardTipo AITDashboardTipo { get; set; }
        public virtual AITPermiso AITPermiso { get; set; }
    }
}
