//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AITMultimedia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AITMultimedia()
        {
            this.AITAvisoCampoValorMultimedia = new HashSet<AITAvisoCampoValorMultimedia>();
            this.AITAvisoMultimedia = new HashSet<AITAvisoMultimedia>();
            this.AITAvisoTareaMultimedia = new HashSet<AITAvisoTareaMultimedia>();
        }
    
        public int CodigoMultimedia { get; set; }
        public int CodigoMultimediaTipo { get; set; }
        public string Path { get; set; }
        public string Nombre { get; set; }
        public string Autor { get; set; }
        public string Descripcion { get; set; }
        public bool Activo { get; set; }
        public bool Eliminado { get; set; }
        public string UsuarioInserto { get; set; }
        public System.DateTime FechaInserto { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AITAvisoCampoValorMultimedia> AITAvisoCampoValorMultimedia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AITAvisoMultimedia> AITAvisoMultimedia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AITAvisoTareaMultimedia> AITAvisoTareaMultimedia { get; set; }
        public virtual AITMultimediaTipo AITMultimediaTipo { get; set; }
    }
}
