//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AITNotificacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AITNotificacion()
        {
            this.AITNotificacionReaccion = new HashSet<AITNotificacionReaccion>();
            this.AITNotificacionVista = new HashSet<AITNotificacionVista>();
            this.AITNotificacionGrupo = new HashSet<AITNotificacionGrupo>();
        }
    
        public int CodigoNotificacion { get; set; }
        public int CodigoNotificacionEstado { get; set; }
        public int CodigoNotificacionTipo { get; set; }
        public string Titulo { get; set; }
        public string DescripcionCorta { get; set; }
        public string Cuerpo { get; set; }
        public System.DateTime FechaEnvio { get; set; }
        public Nullable<System.DateTime> FechaFinEnvio { get; set; }
        public bool Activo { get; set; }
        public bool Eliminado { get; set; }
        public string UsuarioInserto { get; set; }
        public Nullable<System.DateTime> FechaInserto { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
        public string Imagen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AITNotificacionReaccion> AITNotificacionReaccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AITNotificacionVista> AITNotificacionVista { get; set; }
        public virtual AITNotificacionEstado AITNotificacionEstado { get; set; }
        public virtual AITNotificacionTipo AITNotificacionTipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AITNotificacionGrupo> AITNotificacionGrupo { get; set; }
    }
}
