//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AITProblema
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AITProblema()
        {
            this.AITAviso = new HashSet<AITAviso>();
            this.AITEstadoProblema = new HashSet<AITEstadoProblema>();
            this.AITProblemaCausa = new HashSet<AITProblemaCausa>();
            this.AITProblemaServicio = new HashSet<AITProblemaServicio>();
            this.AITSolucion = new HashSet<AITSolucion>();
            this.AITTareaProblemaGrupo = new HashSet<AITTareaProblemaGrupo>();
        }
    
        public int CodigoProblema { get; set; }
        public int CodigoSubEntidad { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public bool Popular { get; set; }
        public int TiempoEsperaEstimado { get; set; }
        public bool Activo { get; set; }
        public bool Eliminado { get; set; }
        public string UsuarioInserto { get; set; }
        public System.DateTime FechaInserto { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
        public Nullable<int> CodigoPlantilla { get; set; }
        public Nullable<int> CodigoPlantillaTareas { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<bool> EsEditable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AITAviso> AITAviso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AITEstadoProblema> AITEstadoProblema { get; set; }
        public virtual AITPlantillaTareas AITPlantillaTareas { get; set; }
        public virtual AITPlantilla AITPlantilla { get; set; }
        public virtual AITSubEntidad AITSubEntidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AITProblemaCausa> AITProblemaCausa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AITProblemaServicio> AITProblemaServicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AITSolucion> AITSolucion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AITTareaProblemaGrupo> AITTareaProblemaGrupo { get; set; }
    }
}
