//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AITReporteBiosalcDetalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AITReporteBiosalcDetalle()
        {
            this.AITReporteBiosalcDetalleVariable = new HashSet<AITReporteBiosalcDetalleVariable>();
        }
    
        public int CodigoReporteDetalle { get; set; }
        public string NombreDetalle { get; set; }
        public int Orden { get; set; }
        public bool Activo { get; set; }
        public bool Eliminado { get; set; }
        public string UsuarioInserto { get; set; }
        public System.DateTime FechaInserto { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
        public int CodigoReporteBiosalc { get; set; }
        public string Icono { get; set; }
        public Nullable<bool> Titulo { get; set; }
    
        public virtual AITReporteBiosalc AITReporteBiosalc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AITReporteBiosalcDetalleVariable> AITReporteBiosalcDetalleVariable { get; set; }
    }
}
