//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AITTareaPlantilla
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AITTareaPlantilla()
        {
            this.AITTareaProblemaGrupo = new HashSet<AITTareaProblemaGrupo>();
        }
    
        public int CodigoTareaPlantilla { get; set; }
        public int CodigoPlantillaTareas { get; set; }
        public int CodigoTareaTipo { get; set; }
        public Nullable<int> CodigoGrupo { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public string Comentario { get; set; }
        public int Orden { get; set; }
        public bool Activo { get; set; }
        public bool Eliminado { get; set; }
        public string UsuarioInserto { get; set; }
        public System.DateTime FechaInserto { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
    
        public virtual AITPlantillaTareas AITPlantillaTareas { get; set; }
        public virtual AITGrupoUsuario AITGrupoUsuario { get; set; }
        public virtual AITTareaTipo AITTareaTipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AITTareaProblemaGrupo> AITTareaProblemaGrupo { get; set; }
    }
}
