//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AITUsuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AITUsuario()
        {
            this.AITAviso = new HashSet<AITAviso>();
            this.AITAvisoTareaCausa = new HashSet<AITAvisoTareaCausa>();
            this.AITAvisoTareaCausa1 = new HashSet<AITAvisoTareaCausa>();
            this.AITAvisoTareaMultimedia = new HashSet<AITAvisoTareaMultimedia>();
            this.AITAvisoTareaMultimedia1 = new HashSet<AITAvisoTareaMultimedia>();
            this.AITAvisoTareaUsuario = new HashSet<AITAvisoTareaUsuario>();
            this.AITAvisoUsuario = new HashSet<AITAvisoUsuario>();
            this.AITEntidadUsuario = new HashSet<AITEntidadUsuario>();
            this.AITNotificacionReaccion = new HashSet<AITNotificacionReaccion>();
            this.AITNotificacionVista = new HashSet<AITNotificacionVista>();
            this.AITRolUsuario = new HashSet<AITRolUsuario>();
            this.AITUsuarioAtributoDetalle = new HashSet<AITUsuarioAtributoDetalle>();
            this.AITUsuarioRedSocial = new HashSet<AITUsuarioRedSocial>();
            this.AITUsuarioTokenDispositivo = new HashSet<AITUsuarioTokenDispositivo>();
        }
    
        public int CodigoUsuario { get; set; }
        public string NombreCompletoUsuario { get; set; }
        public string Usuario { get; set; }
        public bool AutenticacionWindows { get; set; }
        public string Clave { get; set; }
        public bool Activo { get; set; }
        public bool Eliminado { get; set; }
        public string CorreoElectronico { get; set; }
        public string UsuarioInserto { get; set; }
        public System.DateTime FechaInserto { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
        public Nullable<bool> NecesitaCambioDeClave { get; set; }
        public string UsuarioAD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AITAviso> AITAviso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AITAvisoTareaCausa> AITAvisoTareaCausa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AITAvisoTareaCausa> AITAvisoTareaCausa1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AITAvisoTareaMultimedia> AITAvisoTareaMultimedia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AITAvisoTareaMultimedia> AITAvisoTareaMultimedia1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AITAvisoTareaUsuario> AITAvisoTareaUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AITAvisoUsuario> AITAvisoUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AITEntidadUsuario> AITEntidadUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AITNotificacionReaccion> AITNotificacionReaccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AITNotificacionVista> AITNotificacionVista { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AITRolUsuario> AITRolUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AITUsuarioAtributoDetalle> AITUsuarioAtributoDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AITUsuarioRedSocial> AITUsuarioRedSocial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AITUsuarioTokenDispositivo> AITUsuarioTokenDispositivo { get; set; }
    }
}
