//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AIVPermisosPorUsuario
    {
        public int CodigoPermisoAgrupacion { get; set; }
        public string PermisoAgrupacion { get; set; }
        public int CodigoPermiso { get; set; }
        public string Permiso { get; set; }
        public string Descripcion { get; set; }
        public string Llave { get; set; }
        public string Icono { get; set; }
        public int CodigoRol { get; set; }
        public string Rol { get; set; }
        public int CodigoUsuario { get; set; }
        public string Usuario { get; set; }
    }
}
