//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AIVReporteBiosalcPorVariable
    {
        public int CodigoReporteBiosalc { get; set; }
        public string NombreReporte { get; set; }
        public Nullable<int> CodigoReporteDetalle { get; set; }
        public string NombreDetalle { get; set; }
        public string Icono { get; set; }
        public Nullable<bool> TituloDetalle { get; set; }
        public int CodigoReporteDetalleVariable { get; set; }
        public bool Titulo { get; set; }
        public string NombreVariable { get; set; }
        public bool Visible { get; set; }
        public string Campo { get; set; }
        public string VALOR_DIA { get; set; }
        public string VALOR_SAF { get; set; }
        public decimal Operacion { get; set; }
        public decimal VALOR_DIA_REP { get; set; }
        public decimal VALOR_SAF_REP { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public int orden { get; set; }
        public int orden_var { get; set; }
    }
}
