//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LFTEquipoRonda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LFTEquipoRonda()
        {
            this.LFTMiembroEquipoLiga = new HashSet<LFTMiembroEquipoLiga>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdRonda { get; set; }
        public Nullable<int> CodigoUsuarioEntrenador { get; set; }
        public Nullable<decimal> Presupuesto { get; set; }
        public bool Activo { get; set; }
        public bool Eliminado { get; set; }
        public int CodigoUsuarioInserto { get; set; }
        public string UsuarioInserto { get; set; }
        public System.DateTime FechaInserto { get; set; }
        public Nullable<int> CodigoUsuarioModifico { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
    
        public virtual LFTRondaLiga LFTRondaLiga { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LFTMiembroEquipoLiga> LFTMiembroEquipoLiga { get; set; }
    }
}
