//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LFTLiga
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LFTLiga()
        {
            this.LFTCategoriaJugador = new HashSet<LFTCategoriaJugador>();
            this.LFTJugadorLiga = new HashSet<LFTJugadorLiga>();
            this.LFTRondaLiga = new HashSet<LFTRondaLiga>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int CodigoUsuarioAdministrador { get; set; }
        public int IdInstitucion { get; set; }
        public bool Publico { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<int> CantidadRecurrencia { get; set; }
        public string UnidadRecurrencia { get; set; }
        public Nullable<int> CantidadRondas { get; set; }
        public Nullable<bool> Editable { get; set; }
        public Nullable<bool> EditarPlantilla { get; set; }
        public Nullable<decimal> PresupuestoInicial { get; set; }
        public string Password { get; set; }
        public bool Activo { get; set; }
        public bool Eliminado { get; set; }
        public Nullable<int> CodigoUsuarioInserto { get; set; }
        public string UsuarioInserto { get; set; }
        public Nullable<System.DateTime> FechaInserto { get; set; }
        public Nullable<int> CodigoUsuarioModifico { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LFTCategoriaJugador> LFTCategoriaJugador { get; set; }
        public virtual LFTInstitucion LFTInstitucion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LFTJugadorLiga> LFTJugadorLiga { get; set; }
        public virtual LFTUsuario LFTUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LFTRondaLiga> LFTRondaLiga { get; set; }
    }
}
