//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LFTResultadoRonda
    {
        public int Id { get; set; }
        public int IdRonda { get; set; }
        public int IdJugadorLiga { get; set; }
        public int IdMetrica { get; set; }
        public decimal Resultado { get; set; }
        public bool Eliminado { get; set; }
        public int CodigoUsuarioInserto { get; set; }
        public string UsuarioInserto { get; set; }
        public System.DateTime FechaInserto { get; set; }
        public Nullable<int> CodigoUsuarioModifico { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
        public Nullable<decimal> Puntos { get; set; }
        public Nullable<decimal> ValorObtenido { get; set; }
    
        public virtual LFTJugadorLiga LFTJugadorLiga { get; set; }
        public virtual LFTMetricaCategoria LFTMetricaCategoria { get; set; }
        public virtual LFTRondaLiga LFTRondaLiga { get; set; }
    }
}
