//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LFTRondaLiga
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LFTRondaLiga()
        {
            this.LFTEquipoRonda = new HashSet<LFTEquipoRonda>();
            this.LFTResultadoRonda = new HashSet<LFTResultadoRonda>();
            this.LFTHistoriaPrecioRondaJugador = new HashSet<LFTHistoriaPrecioRondaJugador>();
        }
    
        public int Id { get; set; }
        public int IdLiga { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<int> NumeroRonda { get; set; }
        public Nullable<int> Estado { get; set; }
        public bool Activo { get; set; }
        public Nullable<bool> Eliminado { get; set; }
        public Nullable<int> CodigoUsuarioInserto { get; set; }
        public string UsuarioInserto { get; set; }
        public Nullable<System.DateTime> FechaInserto { get; set; }
        public Nullable<int> CodigoUsuarioModifico { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LFTEquipoRonda> LFTEquipoRonda { get; set; }
        public virtual LFTEstadoRonda LFTEstadoRonda { get; set; }
        public virtual LFTLiga LFTLiga { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LFTResultadoRonda> LFTResultadoRonda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LFTHistoriaPrecioRondaJugador> LFTHistoriaPrecioRondaJugador { get; set; }
    }
}
