//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LFTUsuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LFTUsuario()
        {
            this.LFTJugador = new HashSet<LFTJugador>();
            this.LFTLiga = new HashSet<LFTLiga>();
            this.LFTRolUsuario = new HashSet<LFTRolUsuario>();
        }
    
        public int CodigoUsuario { get; set; }
        public string NombreCompletoUsuario { get; set; }
        public string Usuario { get; set; }
        public bool AutenticacionWindows { get; set; }
        public string Clave { get; set; }
        public bool Activo { get; set; }
        public bool Eliminado { get; set; }
        public string CorreoElectronico { get; set; }
        public Nullable<int> CodigoUsuarioInserto { get; set; }
        public string UsuarioInserto { get; set; }
        public System.DateTime FechaInserto { get; set; }
        public Nullable<int> CodigoUsuarioModifico { get; set; }
        public string UsuarioModifico { get; set; }
        public Nullable<System.DateTime> FechaModifico { get; set; }
        public Nullable<bool> NecesitaCambioDeClave { get; set; }
        public string UsuarioAD { get; set; }
        public Nullable<int> IdInstitucion { get; set; }
    
        public virtual LFTInstitucion LFTInstitucion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LFTJugador> LFTJugador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LFTLiga> LFTLiga { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LFTRolUsuario> LFTRolUsuario { get; set; }
    }
}
