//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuariosAD
    {
        public decimal PK { get; set; }
        public string objectsid { get; set; }
        public string Full_Name { get; set; }
        public string Description { get; set; }
        public string EMail { get; set; }
        public string User_Logon_Name { get; set; }
        public string Password_Never_Expires { get; set; }
        public string Enabled { get; set; }
        public string Password_LastSet { get; set; }
        public string employeeid { get; set; }
        public string codigoanterior { get; set; }
        public string proceso { get; set; }
        public string gerencia { get; set; }
        public string area { get; set; }
        public string Department { get; set; }
        public string Office { get; set; }
        public string Telephone_Number { get; set; }
        public string telefonofijo { get; set; }
        public string software { get; set; }
        public string impresoras { get; set; }
        public string scanner { get; set; }
        public string ups { get; set; }
        public string celular { get; set; }
        public string servicetag { get; set; }
        public string modeloequipo { get; set; }
        public string otrosactivos { get; set; }
        public string localeid { get; set; }
        public string gidnumber { get; set; }
    }
}
